import turtle

def among_us(escala):


    amogus = turtle.Turtle()
    amogus.color("red")
    amogus.speed(10)
    amogus.forward(15*escala)
    amogus.left(90)
    amogus.forward(15*escala)
    amogus.right(90)
    amogus.forward(15*escala)
    amogus.right(90)
    amogus.forward(15*escala)
    amogus.left(90)
    amogus.forward(15*escala)
    amogus.left(90)
    amogus.forward(45*escala)
    amogus.left(90)
    amogus.forward(20*escala)
    amogus.right(90)
    amogus.forward(15*escala)
    amogus.right(90)
    amogus.forward(30*escala)
    amogus.right(90)
    amogus.forward(15*escala)
    amogus.right(90)
    amogus.forward(30*escala)
    amogus.right(90)
    amogus.forward(15*escala)
    amogus.right(90)
    amogus.forward(20*escala)
    amogus.left(90)
    amogus.forward(10*escala)
    amogus.left(90)
    amogus.forward(5*escala)
    amogus.right(90)
    amogus.forward(5*escala)
    amogus.left(90)
    amogus.forward(35*escala)
    amogus.left(90)
    amogus.forward(5*escala)
    amogus.right(90)
    amogus.forward(5*escala)
    amogus.left(90)
    amogus.forward(15*escala)
    amogus.right(90)
    amogus.forward(15*escala)
    amogus.left(90)
    amogus.forward(25*escala)
    amogus.left(90)
    amogus.forward(15*escala)
    amogus.right(90)
    amogus.forward(30*escala)

while True:
    among_us(4)